[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = true

[programs.mainnet]
vesting_program = "3XDaifPQuLu23EQ5SnQkkVssxDj4TfCApxtyxsKSA6GU"

[programs.devnet]
vesting_program = "3XDaifPQuLu23EQ5SnQkkVssxDj4TfCApxtyxsKSA6GU"

[programs.localnet]
vesting_program = "3XDaifPQuLu23EQ5SnQkkVssxDj4TfCApxtyxsKSA6GU"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "mainnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
